version: "3"
services:
  postgres-primary-db:
    image: postgres:10.0-alpine
    env_file: .env
    volumes:
      - pg-data-volume:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}"
    networks:
      - my-app-network
volumes:
  pg-data-volume:
networks:
  my-app-network:
